project:
  type: website
  output-dir: _site

website:
  title: "St√©phane Gonzalez"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Research
        href: research.qmd
      - text: Teaching
        href: teaching.qmd
      - text: Contact
        href: contact.qmd

format:
  html:
    include-after-body:
      - assets/js/portrait-rotator.html
